### ISSUE TITLE
How to remove the white highlighted line cursor in VS2019

### ISSUE THREAD

**Issue by Inerska** [gjactat/visual-studio-2017-palenight-theme#1]
Hi, i just installed the nice skin but i hate the white thing 
https://gyazo.com/24936300149f49b4950be4031ed7370d

Can i remove it ? And How ? 

Thanks :)

**Comment by Glitchii** [comment]
I don't know about Visual Studio but **in VScode:**
Put this line in your settings.json file which you can find here `C:\Users\PC_NAME\AppData\Roaming\Code\User\settings.json`

```json
"editor.lineHighlightBorder": "#ff0000",
```
Change the `#ff0000` to the color you want
![unknown](https://user-images.githubusercontent.com/46096865/59462853-7a15fa80-8e1c-11e9-83ac-0de3cdb12d6b.png)

**Comment by Inerska** [comment]
Yeah it's but it's not VSCode

**Comment by xeqlol** [comment]
Tools -> Options -> Text Editor, in the Display group, uncheck "Highlight current line".
