### ISSUE TITLE
Vertical lines in editor not visible

### ISSUE THREAD

**Issue by Feuerhamster** [gjactat/visual-studio-2017-palenight-theme#2]
Hey, I would like to have the vertical lines visible in the editor. 
As an example of which lines I mean: https://i.stack.imgur.com/YJKvg.png

Which property do I have to change so that they have a different color and are visible again in this theme?

**Comment by ebradim** [comment]
Search for **Structure Guide Lines**

If you use Color Theme Editor for Visual Studio , you will see `Text Editor -> Structure Guide Lines -> Background`
![image](https://user-images.githubusercontent.com/50548116/64719036-badae980-d4c7-11e9-930c-55bf1433ea3a.png)
Hope it Helps.

**Comment by Feuerhamster** [comment]
Yes it works!
Thank you.

**Comment by Feuerhamster** [comment]
Yes it works!
Thank you.
