### ISSUE TITLE
Caret In F# Interactive Window is Very Dark

### ISSUE THREAD

**Issue by 7enderhead** [gjactat/visual-studio-2017-palenight-theme#3]
The caret in the F# interactive window has a width of one pixel with black on dark blue background. I cannot see any option to change this caret's color individually. Any ideas?

![image](https://user-images.githubusercontent.com/339726/74321540-b8383500-4d82-11ea-9805-f4ab1dc320a3.png)

**Comment by 7enderhead** [comment]
I'm in VS 2017 Enterprise

**Comment by gjactat** [comment]
Hello !
I no longer use this color theme on my VS2019 Enterprise setup.
You should give a try to this perfect theme generator : https://dainty.site/
You can pick an existing theme or customize an existing one online. Can't beat it ;-)

This is what my F# console looks like with the Dainty dark theme :
![image](https://user-images.githubusercontent.com/1826064/74322814-d010b880-4d84-11ea-8d21-779eb70bcab5.png)

**Comment by 7enderhead** [comment]
Ok, thanks for the tipp. My caret is still black, but that seems to be somewhat color scheme independent...
